---
title: "Processing"
author: "Helen Horkan"
date: "28/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Rsubread")
library('Rsubread')
BiocManager::install("DESeq2")
library('DESeq2') 
install.packages("tidyverse")
library('tidyverse')
install.packages("pheatmap")
library('pheatmap')

##read in counts from featureCounts
total_counts <- read.csv("total_counts.csv")

##assign gene ID as row name
totalcounts <- total_counts %>% remove_rownames %>% column_to_rownames(var="Gene_ID")
countdata <- as.matrix(totalcounts)

##Remove BAMS from col names
colnames(countdata) <- gsub("\\.[sb]am$", "", colnames(countdata))

##make matrix
countdata <- as.matrix(countdata)

##create conditions
(condition <- factor(c(rep("D0", 3), rep("D1", 3), rep("D3", 3), rep("D6", 2))))

##create col data
(coldata <- data.frame(row.names=colnames(countdata), condition))

##create deseq matrix dataset
dds <- DESeqDataSetFromMatrix(countData=round(countdata), colData=coldata, design=~condition)
dds

##run pipeline

dds <- DESeq(dds)

# Plot dispersions
png("qc-dispersions.png", 1000, 1000, pointsize=20)
plotDispEsts(dds, main="Dispersion plot")
dev.off()

# Regularized log transformation for clustering/heatmaps, etc
rld <- rlogTransformation(dds)
head(assay(rld))
hist(assay(rld))

# Colors for plots below
library(RColorBrewer)
(mycols <- brewer.pal(8, "Dark2")[1:length(unique(condition))])

# Sample distance heatmap
sampleDists <- as.matrix(dist(t(assay(rld))))
library(gplots)
png("qc-heatmap-samples.png", w=1000, h=1000, pointsize=20)
heatmap.2(as.matrix(sampleDists), key=F, trace="none",
          col=colorpanel(100, "black", "white"),
          ColSideColors=mycols[condition], RowSideColors=mycols[condition],
          margin=c(10, 10), main="Sample Distance Matrix")
dev.off()

# Principal components analysis

rld_pca <- function (rld, intgroup = "condition", ntop = 500, colors=NULL, legendpos="bottomleft", main="PCA Biplot", textcx=1, ...) {
  require(genefilter)
  require(calibrate)
  require(RColorBrewer)
  rv = rowVars(assay(rld))
  select = order(rv, decreasing = TRUE)[seq_len(min(ntop, length(rv)))]
  pca = prcomp(t(assay(rld)[select, ]))
  fac = factor(apply(as.data.frame(colData(rld)[, intgroup, drop = FALSE]), 1, paste, collapse = " : "))
  if (is.null(colors)) {
    if (nlevels(fac) >= 3) {
      colors = brewer.pal(nlevels(fac), "Paired")
    }   else {
      colors = c("black", "red")
    }
  }
  pc1var <- round(summary(pca)$importance[2,1]*100, digits=1)
  pc2var <- round(summary(pca)$importance[2,2]*100, digits=1)
  pc1lab <- paste0("PC1 (",as.character(pc1var),"%)")
  pc2lab <- paste0("PC1 (",as.character(pc2var),"%)")
  plot(PC2~PC1, data=as.data.frame(pca$x), bg=colors[fac], pch=21, xlab=pc1lab, ylab=pc2lab, main=main, ...)
  with(as.data.frame(pca$x), textxy(PC1, PC2, labs=rownames(as.data.frame(pca$x)), cex=textcx))
  legend(legendpos, legend=levels(fac), col=colors, pch=20)
}
png("qc-pca.png", 1000, 1000, pointsize=20)
rld_pca(rld, colors=mycols, intgroup="condition", xlim=c(-75, 35))
dev.off()


#Gene Heatmaps 

select <- order(rowMeans(counts(dds,normalized=TRUE)), decreasing=TRUE)[1:500]
select

pheatmap(assay(rld)[select,], cluster_rows=TRUE, show_rownames=FALSE, cluster_cols=FALSE, annotation_col = coldata)
geneheatmap

select <- order(rowMeans(counts(dds,normalized=TRUE)), decreasing=TRUE)[1:20000]

pheatmap(assay(rld)[select,], cluster_rows=TRUE, show_rownames=FALSE, cluster_cols=FALSE, annotation_col = coldata)

png("10000_qc-heatmap-genes.png", w=1000, h=1000, pointsize=20)
pheatmap(assay(rld)[select,], cluster_rows=TRUE, show_rownames=FALSE, cluster_cols=FALSE, annotation_col = coldata)
dev.off()


```

