---
title: "D0toD1"
author: "Helen Horkan"
date: "28/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Rsubread")
library('Rsubread')
BiocManager::install("DESeq2")
library('DESeq2') 
install.packages("tidyverse")
library('tidyverse')
install.packages("pheatmap")
library('pheatmap')

##read in counts from featureCounts
total_counts <- read.csv("total_counts.csv")

##assign gene ID as row names
totalcounts <- total_counts %>% remove_rownames %>% column_to_rownames(var="Gene_ID")

##Extract conditions to be analysed
countsD0toD1 <- totalcounts[ ,1:6]
##countsD1toD3 <- total_counts[ ,4:9]
##countsD3toD6 <- total_counts[ ,7:12]

##make matrix
countdata <- as.matrix(countsD0toD1)

##Remove BAMS from col names
colnames(countdata) <- gsub("\\.[sb]am$", "", colnames(countdata))

##make matrix
countdata <- as.matrix(countdata)

##create conditions
(condition <- factor(c(rep("D0", 3), rep("D1", 3))))
##(condition <- factor(c(rep("D1", 3), rep("D3", 3))))
##(condition <- factor(c(rep("D3", 3), rep("D6", 2))))

##create col data
(coldata <- data.frame(row.names=colnames(countdata), condition))

##create deseq matrix dataset
dds <- DESeqDataSetFromMatrix(countData=round(countdata), colData=coldata, design=~condition)
dds

##run pipeline

dds <- DESeq(dds)

# Plot dispersions
png("D0toD1_qc-dispersions.png", 1000, 1000, pointsize=20)
plotDispEsts(dds, main="Dispersion plot")
dev.off()

# Regularized log transformation for clustering/heatmaps, etc
rld <- rlogTransformation(dds)
head(assay(rld))
hist(assay(rld))

# Colors for plots below

library(RColorBrewer)
(mycols <- brewer.pal(8, "Dark2")[1:length(unique(condition))])

# Sample distance heatmap

sampleDists <- as.matrix(dist(t(assay(rld))))
library(gplots)
png("D0toD1_qc-heatmap-samples.png", w=1000, h=1000, pointsize=20)
heatmap.2(as.matrix(sampleDists), key=F, trace="none",
          col=colorpanel(100, "black", "white"),
          ColSideColors=mycols[condition], RowSideColors=mycols[condition],
          margin=c(10, 10), main="Sample Distance Matrix")
dev.off()

# Principal components analysis

rld_pca <- function (rld, intgroup = "condition", ntop = 500, colors=NULL, legendpos="bottomleft", main="PCA Biplot", textcx=1, ...) {
  require(genefilter)
  require(calibrate)
  require(RColorBrewer)
  rv = rowVars(assay(rld))
  select = order(rv, decreasing = TRUE)[seq_len(min(ntop, length(rv)))]
  pca = prcomp(t(assay(rld)[select, ]))
  fac = factor(apply(as.data.frame(colData(rld)[, intgroup, drop = FALSE]), 1, paste, collapse = " : "))
  if (is.null(colors)) {
    if (nlevels(fac) >= 3) {
      colors = brewer.pal(nlevels(fac), "Paired")
    }   else {
      colors = c("black", "red")
    }
  }
  pc1var <- round(summary(pca)$importance[2,1]*100, digits=1)
  pc2var <- round(summary(pca)$importance[2,2]*100, digits=1)
  pc1lab <- paste0("PC1 (",as.character(pc1var),"%)")
  pc2lab <- paste0("PC1 (",as.character(pc2var),"%)")
  plot(PC2~PC1, data=as.data.frame(pca$x), bg=colors[fac], pch=21, xlab=pc1lab, ylab=pc2lab, main=main, ...)
  with(as.data.frame(pca$x), textxy(PC1, PC2, labs=rownames(as.data.frame(pca$x)), cex=textcx))
  legend(legendpos, legend=levels(fac), col=colors, pch=20)
}
png("D0toD1_qc-pca.png", 1000, 1000, pointsize=20)
rld_pca(rld, colors=mycols, intgroup="condition", xlim=c(-75, 35))
dev.off()


# Get differential expression results

##results for various lfc thresholds - change lfcThreshold

resA <- results(dds, lfcThreshold = 0, altHypothesis="greaterAbs", alpha = 0.05)
table(resA$padj<0.05)
## Order by adjusted p-value
resA <- resA[order(resA$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resA), as.data.frame(counts(dds, normalized=TRUE)), by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
resFilt2 <- resdata[which(resdata$padj < 0.05),]
write.csv(resFilt2, file="lfc0_D0toD1_diffexpr-results.csv")


## Examine plot of p-values
histps <- hist(resA$pvalue, breaks=50, col="grey")

## Examine independent filtering
attr(resA, "filterThreshold")
plot(attr(resA,"filterNumRej"), type="b", xlab="quantiles of baseMean", ylab="number of rejections")

## MA plot

maplot <- function (resA, thresh=0.05, labelsig=TRUE, textcx=1, ...) {
  with(res, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(resA, padj<thresh), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(resA, padj<thresh), textxy(baseMean, log2FoldChange, labs=Gene, cex=textcx, col=2))
  }
}
png("D0toD1_diffexpr-maplot.png", 1500, 1000, pointsize=20)
maplot(resdata, main="MA Plot")
dev.off()

## Volcano plot with "significant" genes labeled
volcanoplot <- function (resA, lfcthresh=2, sigthresh=0.05, main="Volcano Plot", legendpos="bottomright", labelsig=TRUE, textcx=1, ...) {
  with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main=main, ...))
  with(subset(resA, padj<sigthresh ), points(log2FoldChange, -log10(pvalue), pch=20, col="red", ...))
  with(subset(resA, abs(log2FoldChange)>lfcthresh), points(log2FoldChange, -log10(pvalue), pch=20, col="orange", ...))
  with(subset(resA, padj<sigthresh & abs(log2FoldChange)>lfcthresh), points(log2FoldChange, -log10(pvalue), pch=20, col="green", ...))
  if (labelsig) {
    require(calibrate)
    with(subset(resA, padj<sigthresh & abs(log2FoldChange)>lfcthresh), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=textcx, ...))
  }
  legend(legendpos, xjust=1, yjust=1, legend=c(paste("FDR<",sigthresh,sep=""), paste("|LogFC|>",lfcthresh,sep=""), "both"), pch=20, col=c("red","orange","green"))
}
png("D0toD1_diffexpr-volcanoplot.png", 1200, 1000, pointsize=20)
volcanoplot(resdata, lfcthresh=1, sigthresh=0.05, textcx=.8, xlim=c(-2.3, 2))
dev.off()

##gene heatmap
select <- order(rowMeans(counts(dds,normalized=TRUE)), decreasing=TRUE)[1:50]
select
df <- as.data.frame(colData(dds)[,c("condition")])
df
pheatmap(assay(rld)[select,], cluster_rows=FALSE, show_rownames=TRUE, cluster_cols=FALSE)
geneheatmap

png("D0toD1_qc-heatmap-genes.png", w=1000, h=1000, pointsize=20)
pheatmap(assay(rld)[select,], cluster_rows=FALSE, show_rownames=TRUE, cluster_cols=FALSE)
dev.off()


```

